const lessonTitle = "游走于两根棍子上的精灵";

const lessonData = [
    // ===== 第1段 =====
    ["马来西亚", "mǎ lái xī yà", "Malaysia", "Malaysia"],
    ["是", "shì", "is", "ialah"],
    ["一个", "yí gè", "a", "sebuah"],
    ["多元民族", "duō yuán mín zú", "multi-racial", "pelbagai kaum"],
    ["的", "de", "", ""],
    ["国家", "guó jiā", "country", "negara"],
    ["，", "", "", ""],
    ["各族人民", "gè zú rén mín", "people of all races", "rakyat pelbagai kaum"],
    ["和睦共处", "hé mù gòng chǔ", "live in harmony", "hidup dalam harmoni"],
    ["，", "", "", ""],
    ["互相", "hù xiāng", "mutually", "saling"],
    ["包容", "bāo róng", "tolerant", "toleransi"],
    ["与", "yǔ", "and", "dan"],
    ["学习", "xué xí", "learn", "belajar"],
    ["彼此", "bǐ cǐ", "each other's", "antara satu sama lain"],
    ["的", "de", "", ""],
    ["文化", "wén huà", "culture", "budaya"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["塔莎", "tǎ shā", "Tasha", "Tasha"],
    ["是", "shì", "is", "ialah"],
    ["可欣", "kě xīn", "Ke Xin", "Ke Xin"],
    ["的", "de", "", ""],
    ["印裔邻居", "yìn yì lín jū", "Indian neighbour", "jiran berbangsa India"],
    ["兼好友", "jiān hǎo yǒu", "and good friend", "dan kawan baik"],
    ["。", "", "", ""],
    ["她", "tā", "She", "Dia"],
    ["不但", "bù dàn", "not only", "bukan sahaja"],
    ["就读于", "jiù dú yú", "studies at", "bersekolah di"],
    ["华小", "huá xiǎo", "Chinese primary school", "sekolah rendah Cina"],
    ["，", "", "", ""],
    ["也", "yě", "but also", "juga"],
    ["热衷于", "rè zhōng yú", "passionate about", "minat terhadap"],
    ["一门", "yì mén", "a", "sejenis"],
    ["历史悠久", "lì shǐ yōu jiǔ", "time-honoured", "bersejarah"],
    ["的", "de", "", ""],
    ["中华民俗技艺", "zhōng huá mín sú jì yì", "Chinese folk art", "kemahiran seni rakyat Cina"],
    ["——", "", "", ""],
    ["扯铃", "chě líng", "Diabolo", "Diabolo"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["一天", "yì tiān", "One day", "Suatu hari"],
    ["，", "", "", ""],
    ["可欣", "kě xīn", "Ke Xin", "Ke Xin"],
    ["在公园", "zài gōng yuán", "at the park", "di taman"],
    ["巧遇", "qiǎo yù", "bumped into", "terserempak dengan"],
    ["在练习扯铃的", "zài liàn xí chě líng de", "practising diabolo", "yang sedang berlatih diabolo"],
    ["塔莎", "tǎ shā", "Tasha", "Tasha"],
    ["，", "", "", ""],
    ["于是", "yú shì", "so", "maka"],
    ["与她", "yǔ tā", "with her", "dengannya"],
    ["聊起", "liáo qǐ", "chatted about", "berbual tentang"],
    ["了她和扯铃的缘分", "le tā hé chě líng de yuán fèn", "her connection with diabolo", "hubungannya dengan diabolo"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["可欣", "kě xīn", "Ke Xin", "Ke Xin"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["塔莎", "tǎ shā", "Tasha", "Tasha"],
    ["，", "", "", ""],
    ["你扯铃的", "nǐ chě líng de", "Your diabolo", "Diabolo awak"],
    ["技术", "jì shù", "skills", "kemahiran"],
    ["练得真棒", "liàn de zhēn bàng", "are really good", "sangat mahir"],
    ["！", "", "", ""],
    ["你怎么", "nǐ zěn me", "How did you", "Bagaimana awak"],
    ["会对扯铃", "huì duì chě líng", "become interested", "berminat terhadap"],
    ["产生兴趣呢", "chǎn shēng xìng qù ne", "in diabolo", "diabolo"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["塔莎", "tǎ shā", "Tasha", "Tasha"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我跟父母", "wǒ gēn fù mǔ", "I went with my parents", "Saya dengan ibu bapa"],
    ["到购物广场", "dào gòu wù guǎng chǎng", "to the shopping mall", "ke pusat beli-belah"],
    ["逛街时", "guàng jiē shí", "when shopping", "ketika berjalan-jalan"],
    ["，", "", "", ""],
    ["表演者", "biǎo yǎn zhě", "performers", "para penghibur"],
    ["高空抛铃", "gāo kōng pāo líng", "high-altitude diabolo throwing", "melambung diabolo tinggi"],
    ["的动作", "de dòng zuò", "moves", "aksi"],
    ["令我驻足", "lìng wǒ zhù zú", "made me stop", "membuatkan saya terhenti"],
    ["，", "", "", ""],
    ["不自觉地", "bù zì jué de", "unconsciously", "secara tidak sedar"],
    ["凑上前去", "còu shàng qián qù", "stepped closer", "mendekat"],
    ["观赏", "guān shǎng", "to watch", "menonton"],
    ["。", "", "", ""],
    ["那是", "nà shì", "That was", "Itulah"],
    ["我第一次", "wǒ dì yī cì", "my first time", "kali pertama saya"],
    ["看到", "kàn dào", "seeing", "melihat"],
    ["这门技艺", "zhè mén jì yì", "this art", "seni ini"],
    ["。", "", "", ""],
    ["四年级那年", "sì nián jí nà nián", "In Year 4", "Pada tahun darjah empat"],
    ["，", "", "", ""],
    ["学校", "xué xiào", "the school", "sekolah"],
    ["成立了", "chéng lì le", "established", "menubuhkan"],
    ["扯铃队", "chě líng duì", "diabolo team", "pasukan diabolo"],
    ["，", "", "", ""],
    ["我便", "wǒ biàn", "I then", "saya pun"],
    ["满腔热情地", "mǎn qiāng rè qíng de", "enthusiastically", "dengan penuh semangat"],
    ["报名了", "bào míng le", "signed up", "mendaftar"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["可欣", "kě xīn", "Ke Xin", "Ke Xin"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["原来如此", "yuán lái rú cǐ", "I see", "Begitu rupanya"],
    ["。", "", "", ""],
    ["扯铃需要", "chě líng xū yào", "What basic skills", "Apa kemahiran asas"],
    ["学什么基本功呢", "xué shén me jī běn gōng ne", "does diabolo require", "yang perlu dipelajari"],
    ["？", "", "", ""],
    ["我对这门技艺", "wǒ duì zhè mén jì yì", "I am a complete", "Saya tentang seni ini"],
    ["的认识", "de rèn shi", "layman", "pengetahuan"],
    ["完全是门外汉啊", "wán quán shì mén wài hàn a", "about this art", "langsung tidak tahu"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["塔莎", "tǎ shā", "Tasha", "Tasha"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我们", "wǒ men", "We", "Kita"],
    ["得先学", "děi xiān xué", "must first learn", "perlu belajar dahulu"],
    ["运铃", "yùn líng", "basic diabolo control", "mengendalikan diabolo"],
    ["，", "", "", ""],
    ["例如", "lì rú", "such as", "contohnya"],
    ["抛", "pāo", "throwing", "melambung"],
    ["、", "", "", ""],
    ["绕", "rào", "wrapping", "memusing"],
    ["、", "", "", ""],
    ["甩", "shuǎi", "swinging", "menghayun"],
    ["、", "", "", ""],
    ["转", "zhuǎn", "spinning", "memutar"],
    ["、", "", "", ""],
    ["缠", "chán", "entangling", "membelit"],
    ["等", "děng", "etc.", "dan lain-lain"],
    ["。", "", "", ""],
    ["有了", "yǒu le", "With", "Setelah mempunyai"],
    ["一定的基础后", "yí dìng de jī chǔ hòu", "a certain foundation", "asas yang kukuh"],
    ["，", "", "", ""],
    ["教练", "jiào liàn", "the coach", "jurulatih"],
    ["会让我们学", "huì ràng wǒ men xué", "will teach us", "akan mengajar kami"],
    ["“", "", "", ""],
    ["蚂蚁上树", "mǎ yǐ shàng shù", "Ants Climbing a Tree", "Semut Memanjat Pokok"],
    ["、", "", "", ""],
    ["金鸡上架", "jīn jī shàng jià", "Golden Rooster on a Perch", "Ayam Emas di Tiang"],
    ["、", "", "", ""],
    ["抛铃", "pāo líng", "Throwing the Diabolo", "Melambung Diabolo"],
    ["、", "", "", ""],
    ["金蝉脱壳", "jīn chán tuō qiào", "Golden Cicada Sheds Its Shell", "Cicak Emas Lepas Kulit"],
    ["、", "", "", ""],
    ["蜘蛛结网", "zhī zhū jié wǎng", "Spider Weaving a Web", "Labah-labah Jaring"],
    ["”", "", "", ""],
    ["等", "děng", "etc.", "dan lain-lain"],
    ["基本招式", "jī běn zhāo shì", "basic moves", "gerakan asas"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["可欣", "kě xīn", "Ke Xin", "Ke Xin"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这名称", "zhè míng chēng", "These names", "Nama-nama ini"],
    ["真有意思", "zhēn yǒu yì si", "are really interesting", "sungguh menarik"],
    ["！", "", "", ""],
    ["要练多久", "yào liàn duō jiǔ", "How long does it take", "Berapa lama perlu"],
    ["才能上手呢", "cái néng shàng shǒu ne", "to master it", "untuk mahir"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    ["塔莎", "tǎ shā", "Tasha", "Tasha"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["基本功", "jī běn gōng", "Basic skills", "Kemahiran asas"],
    ["大概", "dà gài", "about", "dalam"],
    ["三个月", "sān gè yuè", "three months", "tiga bulan"],
    ["就能掌握", "jiù néng zhǎng wò", "can be mastered", "boleh dikuasai"],
    ["。", "", "", ""],
    ["若要", "ruò yào", "If you want", "Jika ingin"],
    ["与其他选手竞技", "yǔ qí tā xuǎn shǒu jìng jì", "compete with other players", "bertanding dengan pemain lain"],
    ["，", "", "", ""],
    ["至少", "zhì shǎo", "at least", "sekurang-kurangnya"],
    ["得练上", "dé liàn shàng", "need to practise", "perlu berlatih"],
    ["一年", "yì nián", "one year", "setahun"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    ["可欣", "kě xīn", "Ke Xin", "Ke Xin"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["真不简单啊", "zhēn bù jiǎn dān a", "That's not easy", "Sungguh tidak mudah"],
    ["！", "", "", ""],
    ["在学习过程中", "zài xué xí guò chéng zhōng", "During the learning process", "Dalam proses pembelajaran"],
    ["曾遇到", "céng yù dào", "did you encounter", "pernah menghadapi"],
    ["什么阻碍吗", "shén me zǔ ài ma", "any obstacles", "apa-apa halangan"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    ["塔莎", "tǎ shā", "Tasha", "Tasha"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["当然有啊", "dāng rán yǒu a", "Of course", "Sudah tentu ada"],
    ["！", "", "", ""],
    ["开始时", "kāi shǐ shí", "At the beginning", "Pada permulaan"],
    ["，", "", "", ""],
    ["动作", "dòng zuò", "movements", "gerakan"],
    ["很不流畅", "hěn bù liú chàng", "were not smooth", "sangat tidak lancar"],
    ["，", "", "", ""],
    ["铃", "líng", "the diabolo", "diabolo"],
    ["总是", "zǒng shì", "always", "selalu"],
    ["掉在地上", "diào zài dì shàng", "fell to the ground", "jatuh ke tanah"],
    ["，", "", "", ""],
    ["不服输的我", "bù fú shū de wǒ", "I who refused to give up", "Saya yang tidak mahu mengalah"],
    ["便", "biàn", "then", "lalu"],
    ["趁闲暇练习", "chèn xián xiá liàn xí", "practised in my free time", "berlatih di masa lapang"],
    ["。", "", "", ""],
    ["尽管", "jǐn guǎn", "Although", "Walaupun"],
    ["练得", "liàn de", "practising until", "berlatih sehingga"],
    ["手臂肌肉酸痛", "shǒu bì jī ròu suān tòng", "arm muscles sore", "otot lengan sakit"],
    ["、", "", "", ""],
    ["手掌粗糙", "shǒu zhǎng cū cāo", "hands rough", "tapak tangan kasar"],
    ["，", "", "", ""],
    ["我仍", "wǒ réng", "I still", "saya masih"],
    ["咬紧牙根", "yǎo jǐn yá gēn", "gritted my teeth", "menggigit gigi"],
    ["，", "", "", ""],
    ["要在挫败中", "yào zài cuò bài zhōng", "to master it despite failures", "untuk menguasai dalam kegagalan"],
    ["掌握好运铃", "zhǎng wò hǎo yùn líng", "master diabolo control", "menguasai kawalan diabolo"],
    ["。", "", "", ""],
    ["父母见", "fù mǔ jiàn", "My parents saw", "Ibu bapa melihat"],
    ["我对扯铃的", "wǒ duì chě líng de", "my dedication and perseverance", "ketekunan dan kegigihan saya"],
    ["执着与毅力", "zhí zhuó yǔ yì lì", "towards diabolo", "terhadap diabolo"],
    ["也", "yě", "also", "juga"],
    ["大感意外呢", "dà gǎn yì wài ne", "were very surprised", "sangat terkejut"],
    ["！", "", "", ""],
    ["很感谢他们", "hěn gǎn xiè tā men", "I'm grateful they", "Saya bersyukur mereka"],
    ["当时", "dāng shí", "at that time", "pada masa itu"],
    ["没阻拦我练习", "méi zǔ lán wǒ liàn xí", "didn't stop me from practising", "tidak menghalang saya berlatih"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    ["可欣", "kě xīn", "Ke Xin", "Ke Xin"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你的家人", "nǐ de jiā rén", "Your family", "Keluarga awak"],
    ["都很支持你呢", "dōu hěn zhī chí nǐ ne", "are very supportive of you", "sangat menyokong awak"],
    ["！", "", "", ""],
    ["那天看了你的表演", "nà tiān kàn le nǐ de biǎo yǎn", "I watched your performance that day", "Hari itu saya tengok persembahan awak"],
    ["，", "", "", ""],
    ["你真的好厉害", "nǐ zhēn de hǎo lì hài", "you were really amazing", "awak sungguh hebat"],
    ["！", "", "", ""],
    ["这是你", "zhè shì nǐ", "This is the result", "Inilah hasil"],
    ["努力耕耘的成果", "nǔ lì gēng yún de chéng guǒ", "of your hard work", "usaha keras awak"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    ["塔莎", "tǎ shā", "Tasha", "Tasha"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["谢谢夸奖", "xiè xiè kuā jiǎng", "Thank you for the compliment", "Terima kasih atas pujian"],
    ["。", "", "", ""],
    ["我相信", "wǒ xiāng xìn", "I believe", "Saya percaya"],
    ["勤能补拙", "qín néng bǔ zhuō", "diligence makes up for lack of talent", "rajin boleh menampung kekurangan"],
    ["，", "", "", ""],
    ["用了", "yòng le", "took", "mengambil"],
    ["两个月的时间", "liǎng gè yuè de shí jiān", "two months", "masa dua bulan"],
    ["学会了", "xué huì le", "learned", "belajar"],
    ["基本招式", "jī běn zhāo shì", "basic moves", "gerakan asas"],
    ["，", "", "", ""],
    ["连教练", "lián jiào liàn", "even the coach", "malah jurulatih"],
    ["都对我", "dōu duì wǒ", "was also", "juga terhadap saya"],
    ["刮目相看呢", "guā mù xiāng kàn ne", "impressed by me", "memandang tinggi"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第14段

    ["可欣", "kě xīn", "Ke Xin", "Ke Xin"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["仅仅两个月的时间", "jǐn jǐn liǎng gè yuè de shí jiān", "In just two months", "Hanya dalam masa dua bulan"],
    ["就取得", "jiù qǔ dé", "you achieved", "sudah mencapai"],
    ["这么好的成果", "zhè me hǎo de chéng guǒ", "such good results", "hasil yang begitu baik"],
    ["，", "", "", ""],
    ["给你一个", "gěi nǐ yí gè", "I give you a", "Saya beri awak satu"],
    ["“赞”", "zàn", "like", "like"],
    ["！", "", "", ""],
    ["这两年来", "zhè liǎng nián lái", "Over these two years", "Dua tahun ini"],
    ["，", "", "", ""],
    ["你也", "nǐ yě", "you have also", "awak juga"],
    ["代表扯铃队", "dài biǎo chě líng duì", "represented the diabolo team", "mewakili pasukan diabolo"],
    ["出征了吧", "chū zhēng le ba", "in competitions", "bertanding"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第15段

    ["塔莎", "tǎ shā", "Tasha", "Tasha"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["是的", "shì de", "Yes", "Ya"],
    ["。", "", "", ""],
    ["这两年", "zhè liǎng nián", "These two years", "Dua tahun ini"],
    ["，", "", "", ""],
    ["教练", "jiào liàn", "the coach", "jurulatih"],
    ["不但", "bù dàn", "not only", "bukan sahaja"],
    ["给予我", "jǐ yǔ wǒ", "gave me", "memberi saya"],
    ["参与演出", "cān yù yǎn chū", "performance", "peluang menyertai"],
    ["的机会", "de jī huì", "opportunities", "persembahan"],
    ["，", "", "", ""],
    ["还", "hái", "but also", "malah"],
    ["鼓励我", "gǔ lì wǒ", "encouraged me", "menggalakkan saya"],
    ["多参加比赛", "duō cān jiā bǐ sài", "to participate in more competitions", "banyak sertai pertandingan"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第16段

    ["可欣", "kě xīn", "Ke Xin", "Ke Xin"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这些经验", "zhè xiē jīng yàn", "These experiences", "Pengalaman-pengalaman ini"],
    ["让你", "ràng nǐ", "have made you", "membuatkan awak"],
    ["在学习扯铃上", "zài xué xí chě líng shàng", "in learning diabolo", "dalam belajar diabolo"],
    ["有什么体会", "yǒu shén me tǐ huì", "what insights", "apa pengajaran"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第17段

    ["塔莎", "tǎ shā", "Tasha", "Tasha"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我感觉", "wǒ gǎn jué", "I feel", "Saya rasa"],
    ["身手更敏捷了", "shēn shǒu gèng mǐn jié le", "more agile", "lebih cergas"],
    ["。", "", "", ""],
    ["当我", "dāng wǒ", "When I", "Apabila saya"],
    ["成功掌握", "chéng gōng zhǎng wò", "successfully master", "berjaya menguasai"],
    ["较高难度的招式", "jiào gāo nán dù de zhāo shì", "more difficult moves", "gerakan yang lebih sukar"],
    ["，", "", "", ""],
    ["那种", "nà zhǒng", "that kind of", "jenis"],
    ["成就感", "chéng jiù gǎn", "sense of achievement", "perasaan pencapaian"],
    ["和满足感", "hé mǎn zú gǎn", "and satisfaction", "dan kepuasan"],
    ["真的", "zhēn de", "truly", "benar-benar"],
    ["非笔墨能形容", "fēi bǐ mò néng xíng róng", "beyond words", "tidak dapat digambarkan"],
    ["。", "", "", ""],
    ["另外", "lìng wài", "Besides", "Selain itu"],
    ["，", "", "", ""],
    ["在集训时", "zài jí xùn shí", "during training camps", "semasa berkumpulan"],
    ["，", "", "", ""],
    ["我也深感", "wǒ yě shēn gǎn", "I also deeply feel", "saya juga merasai"],
    ["与队友合作", "yǔ duì yǒu hé zuò", "teamwork with teammates", "bekerjasama dengan rakan sepasukan"],
    ["的重要性", "de zhòng yào xìng", "is important", "kepentingan"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第18段

    ["可欣", "kě xīn", "Ke Xin", "Ke Xin"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["没想到", "méi xiǎng dào", "I didn't expect", "Tidak menyangka"],
    ["小小的扯铃", "xiǎo xiǎo de chě líng", "such a small diabolo", "diabolo yang kecil"],
    ["能让你", "néng ràng nǐ", "can bring you", "boleh memberi awak"],
    ["收获满满", "shōu huò mǎn mǎn", "so much收获", "begitu banyak hasil"],
    ["，", "", "", ""],
    ["那你", "nà nǐ", "then what", "jadi awak"],
    ["对自己", "duì zì jǐ", "are your expectations", "terhadap diri sendiri"],
    ["在扯铃方面", "zài chě líng fāng miàn", "for yourself in diabolo", "dalam bidang diabolo"],
    ["有什么期许呢", "yǒu shén me qī xǔ ne", "what are they", "apa harapan"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第19段

    ["塔莎", "tǎ shā", "Tasha", "Tasha"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我期许", "wǒ qī xǔ", "I hope", "Saya berharap"],
    ["把技术", "bǎ jì shù", "to improve", "kemahiran"],
    ["练得更纯熟", "liàn de gèng chún shú", "my skills", "lebih mahir"],
    ["，", "", "", ""],
    ["并在", "bìng zài", "and in", "dan pada"],
    ["几年后", "jǐ nián hòu", "a few years", "beberapa tahun kemudian"],
    ["参加", "cān jiā", "participate in", "menyertai"],
    ["国际扯铃锦标赛", "guó jì chě líng jǐn biāo sài", "international diabolo championship", "kejohanan diabolo antarabangsa"],
    ["。", "", "", ""],
    ["希望", "xī wàng", "I hope", "Harap"],
    ["届时", "jiè shí", "by then", "pada masa itu"],
    ["能获得", "néng huò dé", "can achieve", "boleh mencapai"],
    ["辉煌的成绩", "huī huáng de chéng jì", "glorious results", "keputusan yang cemerlang"],
    ["，", "", "", ""],
    ["拿下", "ná xià", "win", "meraih"],
    ["一枚奖牌", "yì méi jiǎng pái", "a medal", "sepingat"],
    ["，", "", "", ""],
    ["为国争光", "wèi guó zhēng guāng", "bring honour to the country", "mengharumkan nama negara"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第20段

    ["可欣", "kě xīn", "Ke Xin", "Ke Xin"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["祝你", "zhù nǐ", "Wish you", "Semoga awak"],
    ["早日实现", "zǎo rì shí xiàn", "achieve soon", "cepat mencapainya"],
    ["这个宏愿", "zhè ge hóng yuàn", "this aspiration", "cita-cita ini"],
    ["。", "", "", ""],
    ["啊", "a", "Ah", "Ah"],
    ["，", "", "", ""],
    ["晚餐时间", "wǎn cān shí jiān", "Dinner time", "Waktu makan malam"],
    ["快到了", "kuài dào le", "is approaching", "hampir tiba"],
    ["，", "", "", ""],
    ["我们该回家喽", "wǒ men gāi huí jiā lou", "we should go home", "kita patut pulang"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第21段

    ["塔莎", "tǎ shā", "Tasha", "Tasha"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["好", "hǎo", "Okay", "Baik"],
    ["，", "", "", ""],
    ["我们下回", "wǒ men xià huí", "We'll chat again", "Kita lain kali"],
    ["再聊啊", "zài liáo a", "next time", "berbual lagi"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第22段

    ["可欣", "kě xīn", "Ke Xin", "Ke Xin"],
    ["想起", "xiǎng qǐ", "remembered", "teringat"],
    ["和塔莎的对话", "hé tǎ shā de duì huà", "the conversation with Tasha", "perbualan dengan Tasha"],
    ["，", "", "", ""],
    ["不禁赞叹", "bù jīn zàn tàn", "couldn't help but admire", "tidak dapat menahan kekaguman"],
    ["：", "", "", ""],
    ["两根", "liǎng gēn", "Two", "Dua batang"],
    ["小小的木棍", "xiǎo xiǎo de mù gùn", "small wooden sticks", "kayu kecil"],
    ["、", "", "", ""],
    ["一条绳", "yì tiáo shéng", "a rope", "seutas tali"],
    ["和", "hé", "and", "dan"],
    ["一只铃", "yì zhī líng", "a diabolo", "sebiji diabolo"],
    ["的组合", "de zǔ hé", "combination", "gabungan"],
    ["，", "", "", ""],
    ["竟给塔莎", "jìng gěi tǎ shā", "actually brought Tasha", "telah memberi Tasha"],
    ["带来", "dài lái", "so much", "membawa"],
    ["那么多的收获和体悟", "nà me duō de shōu huò hé tǐ wù", "gain and insights", "begitu banyak hasil dan pengajaran"],
    ["！", "", "", ""],
    ["希望", "xī wàng", "I hope", "Harap"],
    ["这游走于", "zhè yóu zǒu yú", "this spirit that dances", "roh yang bermain di"],
    ["两根木棍之上", "liǎng gēn mù gùn zhī shàng", "on two wooden sticks", "atas dua batang kayu"],
    ["的精灵", "de jīng líng", "can continue", "ini"],
    ["，", "", "", ""],
    ["能继续", "néng jì xù", "to flourish", "dapat terus"],
    ["在我国", "zài wǒ guó", "in our country", "di negara kita"],
    ["发扬光大", "fā yáng guāng dà", "and prosper", "berkembang maju"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["佚名", "yì míng", "Anonymous", "Tanpa Nama"],
    ["《", "", "", ""],
    ["游走于两根棍子上的精灵", "yóu zǒu yú liǎng gēn gùn zi shàng de jīng líng", "The Spirit Dancing on Two Sticks", "Roh yang Menari di Atas Dua Batang Kayu"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
